name: Development Deployment

on: [push]

jobs:
  build:
    name: Build Code

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Code
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn
      working-directory: ./wp-content/themes/cleverclip
    - name: Build code
      run: yarn build
      working-directory: ./wp-content/themes/cleverclip
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: .


  deploy:
    name: Deploy to development

    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEVELOPMENT_HOST }}
        username: ${{ secrets.DEVELOPMENT_USERNAME }}
        key: ${{ secrets.DEVELOPMENT_KEY }}
        source: "."
        target: "/var/www/deployment-test"
