name: Development Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy the code

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn
      working-directory: ./wp-content/themes/cleverclip
    - name: Build code
      run: yarn build
      working-directory: ./wp-content/themes/cleverclip
    - name: Deploy build to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEVELOPMENT_HOST }}
        username: ${{ secrets.DEVELOPMENT_USERNAME }}
        key: ${{ secrets.DEVELOPMENT_KEY }}
        source: "."
        target: "/var/www/html"
