name: Development Deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Code
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn
      working-directory: ./wp-content/themes/cleverclip
    - run: yarn build
      working-directory: ./wp-content/themes/cleverclip
      
      
  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USERNAME }}
        key: ${{ secrets.DEPLOYMENT_KEY }}
        source: "."
        target: "/var/www/deployment-test"
