name: Production Deployment

on: [push]

jobs:
  build-and-deploy:
    name: Build and deploy

    if: contains(github.event.head_commit.message, '[production]')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn
      working-directory: ./wp-content/themes/cleverclip
    - name: Build code
      run: yarn build
      working-directory: ./wp-content/themes/cleverclip
    - name: Deploy build to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_KEY }}
        source: "."
        target: "/var/www/deployment-test"

  purge-cdn:
    name: Purge CDN cache

    needs: [build-and-deploy]

    runs-on: ubuntu-latest

    steps:
    - name: purge cdn cache
      run: |
        STACKPATH_ACCESS_TOKEN=$(curl --request POST \
        --url https://gateway.stackpath.com/identity/v1/oauth2/token \
        --header 'content-type: application/json' \
        --data '{
          "client_id": "${{ secrets.STACKPATH_CLIENT_ID }}",
          "client_secret": "${{ secrets.STACKPATH_CLIENT_SECRET }}",
          "grant_type": "client_credentials"
        }' | jq -r '.access_token')
        curl --request POST \
        --url https://gateway.stackpath.com/cdn/v1/stacks/${{ secrets.STACKPATH_STACK_ID }}/purge \
        --header "accept: application/json" \
        --header "authorization: Bearer ${STACKPATH_ACCESS_TOKEN}" \
        --header "content-type: application/json" \
        --data '{"items":[{"url":"//cleverclipstudios.com/wp-content", "recursive":true}]}'
